# Generated by Django 4.2.11 on 2024-03-17 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingType',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeMark',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSens',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('MetricUnits', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserObject',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Active', models.BooleanField(default=False)),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=250)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typesens')),
            ],
        ),
        migrations.CreateModel(
            name='SensObject',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
                ('Sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='UserDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=250)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Role', 'User')},
            },
        ),
        migrations.CreateModel(
            name='TypeSensUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Priority', models.IntegerField()),
                ('DrawingType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.drawingtype')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typesens')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('User', 'Type')},
            },
        ),
        migrations.CreateModel(
            name='TypeSensRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typesens')),
            ],
            options={
                'unique_together': {('Role', 'Type')},
            },
        ),
        migrations.CreateModel(
            name='DataSens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.FloatField()),
                ('Sens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensor')),
                ('Time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.timemark')),
            ],
            options={
                'unique_together': {('Sens', 'Time')},
            },
        ),
    ]
