# Generated by Django 4.2.11 on 2024-04-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_typescount_alter_typesensuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesensuser',
            name='CountVals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='typesensuser',
            name='TypeCount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typescount'),
        ),
    ]
