# Generated by Django 4.2.11 on 2024-04-24 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_typesensuser_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountVals', models.IntegerField()),
                ('Priority', models.IntegerField(default=0)),
                ('DrawingType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.drawingtype')),
            ],
        ),
        migrations.CreateModel(
            name='SensGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
                ('Sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensor')),
            ],
        ),
        migrations.DeleteModel(
            name='TypeSensUser',
        ),
        migrations.AddField(
            model_name='groupuser',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensgroup'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='TypeCount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typescount'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('User', 'Group', 'DrawingType')},
        ),
    ]
