# Generated by Django 4.2.11 on 2024-04-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_groups_groupuser_sensgroup_delete_typesensuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups'),
        ),
    ]
