# Generated by Django 4.2.11 on 2024-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_groupuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
