# Generated by Django 4.2.11 on 2024-04-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_groups_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupUser',
        ),
    ]
