# Generated by Django 4.2.11 on 2024-04-29 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_delete_groupuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CountVals', models.IntegerField()),
                ('Priority', models.IntegerField(default=0)),
                ('DrawingType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.drawingtype')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
                ('TypeCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typescount')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('User', 'Group', 'DrawingType')},
            },
        ),
    ]
