# Generated by Django 4.2.11 on 2024-05-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_groupuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typescount',
            old_name='Nume',
            new_name='Name',
        ),
    ]
