# Generated by Django 4.2.11 on 2024-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_nume_typescount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
