# Generated by Django 4.2.11 on 2024-06-10 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_groupuser_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('User', 'Group')},
        ),
    ]
