# Generated by Django 4.2.11 on 2024-06-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_groupuser_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together=set(),
        ),
    ]
